//
//  version.hpp
//  DocumentCropper
//
//  Created by Denis Silko on 11/08/19.
//  Copyright © 2019 Paycasso. All rights reserved.
//

#ifndef version_h
#define version_h

#define DOCUMENT_CROPPER_VERSION_MAJOR    1
#define DOCUMENT_CROPPER_VERSION_MINOR    5
#define DOCUMENT_CROPPER_VERSION_REVISION 1
#define DOCUMENT_CROPPER_VERSION_STATUS   ""

#define DOCUMENT_CROPPERAUX_STR_EXP(__A)  #__A
#define DOCUMENT_CROPPERAUX_STR(__A)      DOCUMENT_CROPPERAUX_STR_EXP(__A)

#define DOCUMENT_CROPPERAUX_STRW_EXP(__A)  L ## #__A
#define DOCUMENT_CROPPERAUX_STRW(__A)      DOCUMENT_CROPPERAUX_STRW_EXP(__A)

#define DOCUMENT_CROPPER_VERSION          DOCUMENT_CROPPERAUX_STR(DOCUMENT_CROPPER_VERSION_MAJOR) "." DOCUMENT_CROPPERAUX_STR(DOCUMENT_CROPPER_VERSION_MINOR) "." DOCUMENT_CROPPERAUX_STR(DOCUMENT_CROPPER_VERSION_REVISION) DOCUMENT_CROPPER_VERSION_STATUS

#endif /* version_h */
